name: Generate Release Notes

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'
      version:
        description: 'Release version'
        required: true

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install towncrier requests

      - name: Generate news fragments
        run: python generate_news_fragments.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.event.inputs.branch }}

      - name: Build release notes
        run: |
        pwd
        towncrier build --version ${{ github.event.inputs.version }}
