name: Generate Release Notes

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'
      version:
        description: 'Release version'
        required: true

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install towncrier requests

      - name: Debug
        run: |
          ls -R
          pwd

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/my_package" >> $GITHUB_ENV

      - name: Generate news fragments
        run: python generate_news_fragments.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.event.inputs.branch }}

      - name: Build release notes
        run: |
          pwd
          towncrier build --version ${{ github.event.inputs.version }} --yes

      - uses: EndBug/add-and-commit@v9
        with:
          ref: ${{ github.ref }}
          add: '["NEWS.rst", "newsfragments"]'
          author_name: am2558
          author_email: am2558@cornell.edu
          commit: --signoff
          committer_name: am2558
          committer_email: am2558@cornell.edu
          cwd: "."
          default_author: github_actor
          fetch: true
          message: "increment version number"
          pathspec_error_handling: exitImmediately
          push: true
