name: Automatic PR Labeler

on:
  pull_request:
    types: [opened, reopened]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch type from PR title
        id: branch-type
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Branch name: $BRANCH_NAME"
          if [[ "$BRANCH_NAME" =~ BUGFIX-AQC-[0-9]+-.+ ]]; then
            echo "::set-output name=LABEL::Bugfix Version"
          elif [[ "$BRANCH_NAME" =~ FEATURE-AQC-[0-9]+-.+ ]]; then
            echo "::set-output name=LABEL::Minor Version"
          elif [[ "$BRANCH_NAME" =~ TQA-[0-9]+-.+ ]]; then
            echo "::set-output name=LABEL::Bugfix Version"
          else
            echo "No specific branch pattern matched."
            echo "::set-output name=LABEL::"
          fi

      - name: Apply label to PR
        if: steps.branch-type.outputs.LABEL != ''
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const label = "${{ steps.branch-type.outputs.LABEL }}"
            const issue_number = context.issue.number;
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              labels: [label]
            })
