name: CI Check for Newsfragments

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  newsfragment_check:
    runs-on: ubuntu-latest
    name: Check for newsfragments
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Ensure newsfragments is non-empty
        run: |
          CHANGED_FILES=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | grep '^newsfragments/')
          if [ -z "$CHANGED_FILES" ]; then
            echo "No newsfragments files were changed! Please add a news fragment."
            exit 1
          else
            echo "Found the following newsfragments changes:"
            echo "$CHANGED_FILES"
          fi

      - name: Validate newsfragment file names
        run: |
          INVALID_FILES=""
          for file in $(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | grep '^newsfragments/'); do
            BASENAME=$(basename "$file")
            if [[ ! "$BASENAME" =~ (AQC|TQA|BUGFIX|QNO)-[0-9]+-.* ]]; then
              INVALID_FILES="$INVALID_FILES\n$file"
            fi
          done

          if [ -n "$INVALID_FILES" ]; then
            echo -e "The following newsfragment files have invalid names:$INVALID_FILES"
            exit 1
          else
            echo "All newsfragment files have valid names."
          fi
