name: CI Check for Newsfragments

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  newsfragment_check:
    runs-on: ubuntu-latest
    name: Check for newsfragments
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get PR Author
        id: get-author
        run: echo "author=$(jq -r '.pull_request.user.login' < ${GITHUB_EVENT_PATH})" >> $GITHUB_ENV

      - name: Skip job for bot PRs
        if: ${{ env.author == 'github-actions[bot]' }}
        run: echo "Skipping job for bot PRs" && exit 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Ensure newsfragments is non-empty
        run: |
          CHANGED_FILES=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | grep '^newsfragments/')
          if [ -z "$CHANGED_FILES" ]; then
            echo "No newsfragments files were changed! Please add a news fragment."
            exit 1
          else
            echo "Found the following newsfragments changes:"
            echo "$CHANGED_FILES"
          fi

      - name: Validate newsfragment file names
        id: validate_names
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          BRANCH_NUMBER=$(echo "$BRANCH_NAME" | sed -E 's/.*-([0-9]+).*/\1/')
          INVALID_FILES=""
          for file in $(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | grep '^newsfragments/' | grep -v '.gitignore'); do
            BASENAME=$(basename "$file")
            if [[ ! "$BASENAME" =~ ^.*-$BRANCH_NUMBER\..* ]]; then
              INVALID_FILES="$INVALID_FILES\n$file"
            fi
          done

          echo "::set-output name=invalid_files::$INVALID_FILES"

      - name: Create comment on PR if invalid files
        if: steps.validate_names.outputs.invalid_files != ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            The following newsfragment files have invalid names:${{ steps.validate_names.outputs.invalid_files }}
            Each file must match the pattern: *-JIRA-ticket-number.extension
            Refer to the README.md for detailed validation criteria.
