name: Protect Main and Auto-version
on:
  pull_request:
    types:
      - closed

jobs:

  close:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      closed: ${{ steps.close.outputs.closed }}
      issue: ${{ steps.issue.outputs.issue }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Check if valid feature or bugfix branch
        id: check_branch
        run: |
          if [[ '${{ github.head_ref }}' =~ (FEATURE|BUGFIX)-AQC-[0-9]+-.+ ]]; then
            echo "VALID_BRANCH_NAME=true" >> $GITHUB_ENV
            if [[ '${{ github.head_ref }}' =~ FEATURE.* ]]; then
              echo "GH_ISSUE_TYPE=FEATURE" >> $GITHUB_ENV
            elif [[ '${{ github.head_ref }}' =~ BUGFIX.* ]]; then
              echo "GH_ISSUE_TYPE=BUGFIX" >> $GITHUB_ENV
            fi
          else
            echo "VALID_BRANCH_NAME=false" >> $GITHUB_ENV
          fi
      - name: Set PR_LABEL environment variable 
        run: |
            PR_LABEL_JSON=${{ toJson(github.event.pull_request.labels.*.name) }}
            PR_LABEL=$(echo $PR_LABEL_JSON | jq -r '.[0]')
            echo $PR_LABEL
            echo "PR_LABEL=$PR_LABEL" >> $GITHUB_ENV
         #triggered on merge to main
      - name: Increment version number based on branch name
        if: env.VALID_BRANCH_NAME == 'true' 
        
       
        run: |
          python -c "
          import os
          import re
          import json
          version_file='version.txt'
          print(f'::debug::{os.getcwd()}')
          
          file =  open(version_file, 'r')
          version_lines = file.readlines()
          file.close()
          version = version_lines[0].strip()
          print(f'::debug::{version} version file before incrementing')
          match = re.match(r'(\d+)\.(\d+)\.(\d+)', version)
          if not match: 
            raise ValueError(match)
          if match:
          #apply label to PR
              major = match.group(1)
              minor = match.group(2)
              patch = match.group(3)
              pr_label = os.getenv('PR_LABEL')
              print(f'PR Label: {pr_label}')
              if (len(pr_labels) == 1):
                if pr_label[0] == 'Major Version':
                    major = int(major) + 1
                elif pr_labels[0] == 'Minor Version':
                    minor = int(minor) + 1
                elif pr_labels[0] == 'Bugfix Version':
                    patch = int(patch) + 1
              else:
                if '${{ env.GH_ISSUE_TYPE }}' == 'FEATURE':
                    minor = int(minor) + 1
                elif '${{ env.GH_ISSUE_TYPE }}' == 'BUGFIX':
                    patch = int(patch) + 1
              new_version = f'{major}.{minor}.{patch}'
              with open(version_file, 'w') as file:
                  file.write(new_version)
          else:
              raise ValueError('Version format not recognized: ' + version)"
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          ref: main
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: "version.txt"

          # The name of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_name: am2558

          # The email of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_email: am2558@cornell.edu

          # Additional arguments for the git commit command. The --message argument is already set by the message input.
          # Default: ''
          commit: --signoff

          # The name of the custom committer you want to use, if different from the author of the commit.
          # Default: the name of the author (set with either author_name or default_author)
          committer_name: am2558

          # The email of the custom committer you want to use, if different from the author of the commit.
          # Default: the email of the author (set with either author_email or default_author)
          committer_email: am2558@cornell.edu

          # The local path to the directory where your repository is located. You should use actions/checkout first to set it up.
          # Default: '.'
          cwd: "."

          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          # Default: github_actor
          default_author: github_actor

          # Arguments for the git fetch command. If set to false, the action won't fetch the repo.
          # For more info as to why fetching is usually recommended, please see the "Performance on large repos" FAQ.
          # Default: --tags --force
          fetch: true

          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: "increment version number"

          new_branch: main

          # The way the action should handle pathspec errors from the add and remove commands. Three options are available:
          # - ignore -> errors will be logged but the step won't fail
          # - exitImmediately -> the action will stop right away, and the step will fail
          # - exitAtEnd -> the action will go on, every pathspec error will be logged at the end, the step will fail.
          # Default: ignore
          pathspec_error_handling: exitImmediately

          # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
          # Default: true
          push: true