name: Updated Quay
on:
  workflow_dispatch:

jobs:
  close:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      closed: ${{ steps.close.outputs.closed }}
      issue: ${{ steps.issue.outputs.issue }}
    steps:
      - name: Create GitHub Tag
        id: tag_version
        run: |
          echo "New version: ${{ env.NEW_VERSION }}"
          git tag v${{ env.NEW_VERSION }}
          git push origin v${{ env.NEW_VERSION }}

      - name: Read Release Notes
        id: release_notes
        run: |
          RELEASE_NOTES=$(cat NEWS.rst)
          echo "::set-output name=notes::$RELEASE_NOTES"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.NEW_VERSION }}
          name: Release v${{ env.NEW_VERSION }}
          body: ${{ steps.release_notes.outputs.notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: EndBug/add-and-commit@v9
        with:
          ref: ${{ github.ref }}
          add: '["code/django/version.txt", "NEWS.rst", "newsfragments"]'
          author_name: 'Github Actions - Auto-version / Releasing Workflow'
          author_email: actions@github.com
          commit: --signoff
          committer_name: 'Github Actions - Auto-version / Releasing Workflow'
          committer_email: actions@github.com
          cwd: "."
          default_author: github_actor
          fetch: true
          message: "increment version number"
          pathspec_error_handling: exitImmediately
          push: true

      - name: Login to Quay.io 
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
              quay.io/am2558/aliro-orchestrator-fake:${{ env.NEW_VERSION }}
              quay.io/am2558/aliro-orchestrator-fake:latest

      #tag the release as a release candidate
      - name: Tag as release candidate
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: quay.io/am2558/aliro-orchestrator-fake:${{ env.NEW_VERSION }}-rc
