name: Updated Quay
on:
  workflow_dispatch:

jobs:
  close:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      closed: ${{ steps.close.outputs.closed }}
      issue: ${{ steps.issue.outputs.issue }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Read version number
        id: read_version
        run: |
          VERSION=$(cat code/django/VERSION.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=VERSION::$VERSION"
          
      - name: Create GitHub Tag
        id: tag_version
        run: |
          echo "New version: ${{ steps.read_version.outputs.VERSION }}"
          git tag v${{ steps.read_version.outputs.VERSION }}
          git push origin v${{ steps.read_version.outputs.VERSION }}

      - name: Read Release Notes
        id: release_notes
        run: |
          RELEASE_NOTES=$(cat NEWS.rst)
          echo "::set-output name=notes::$RELEASE_NOTES"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.read_version.outputs.VERSION }}
          name: Release v${{ steps.read_version.outputs.VERSION }}
          body: ${{ steps.release_notes.outputs.notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Quay.io 
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
              quay.io/am2558/aliro-orchestrator-fake:${{ steps.read_version.outputs.VERSION }}
              quay.io/am2558/aliro-orchestrator-fake:latest

      - name: Tag as release candidate
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: quay.io/am2558/aliro-orchestrator-fake:${{ steps.read_version.outputs.VERSION }}-rc
